# Generated by Django 6.0.3 on 2026-04-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nutritionist',
            name='surname',
        ),
    ]
